### PR TITLE
Updating endpoints for food search

### PR DESCRIPTION
**Pull request by garv5014**
Made the end point for get food by Id. The USDA has different ways of representing the same information in different json formats that is what the json converter is trying to solve. Right now it is only working with FULL format on the USDA call. The abridged format doesn't give a lot of information but it might be enough. We can talk about it and see which one we want to use.

### CODE REVIEW

**Comment by garv5014** [comment]
I merged foodsearch into this branch thinking that I would make it so there would be no conflicts with main because foodsearch was about to be merged into main. But there are a bunch of changes I didn't make in nutrinova-ui that, I would imagine, came from the foodsearch merge. I that an issue?

**Comment by andrewbengordon** [comment]
I was just about to ask. But I think that the major changes were just from Caleb adjusting the folder structure of the project. I image if you merged his changes, they're probably fairly up to date. You might want to roll back just in case he decides to make a few more before he merges.

**Comment by Cwighty** [comment]
> I merged foodsearch into this branch thinking that I would make it so there would be no conflicts with main because foodsearch was about to be merged into main. But there are a bunch of changes I didn't make in nutrinova-ui that, I would imagine, came from the foodsearch merge. I that an issue?

If you just merge main into what you have now I think they will disappear?

**Review by Cwighty — APPROVED** [review]
Way to go with the error handling/logging with the endpoints!

**Pull request merged**
